### ISSUE TITLE
请问为什么开发者账号不可以申请了？

### ISSUE THREAD

**Issue by solomonxie** [liluo/douban-client#9]
近期正在认认真真的学习豆瓣API文档，
准备好好学习一下呢， 
结果连账号都申请不了…………………… 
这一盆冷水啊
望回复，谢谢。

**Comment by liluo** [comment]
我已经离职蛮久了，具体情况你关注一下  http://www.douban.com/people/liluoliluo/status/1765909994/

**Comment by solomonxie** [comment]
实在感谢！只能看那边有没有人回复啦~
